const GAMES = [
  {
    id: 1,
    title: "TEST",
    description: "By: ME",
    thumbnail: "#",
    url: "#",
  },
  {
id: 2,
title: "Amanda The Adventurer",
description: "By: bread",
thumbnail: "/thumbs/2.png",
url: "/games/2/index.html",
  },
  {
id: 3,
title: "Andy's Apple Farm",
description: "By: bread",
thumbnail: "/thumbs/3.png",
url: "/games/3/index.html",
  },
  {
id: 4,
title: "Antonblast",
description: "By: burnedpopcorn",
thumbnail: "/thumbs/4.png",
url: "/games/4/index.html",
  },
  {
id: 5,
title: "A Difficult Game About Climbing",
description: "By: bread",
thumbnail: "/thumbs/5.png",
url: "/games/5/index.html",
  },
  {
id: 6,
title: "Apotheon",
description: "By: gurtmuncher",
thumbnail: "/thumbs/6.png",
url: "/games/6/index.html",
  },
  {
id: 7,
title: "Approaches",
description: "By: shayder",
thumbnail: "/thumbs/7.png",
url: "/games/7/index.html",
  },
  {
id: 8,
title: "Arco",
description: "By: cirsius",
thumbnail: "/thumbs/8.png",
url: "/games/8/index.html",
  },
  {
id: 9,
title: "Balatro",
description: "By: W0W53R",
thumbnail: "/thumbs/9.png",
url: "/games/9/index.html",
  },
  {
id: 10,
title: "Baldi's Basics Birthday Bash",
description: "By: crackers",
thumbnail: "/thumbs/10.png",
url: "/games/10/index.html",
  },
  {
id: 11,
title: "Baldi's Basics Classic Remastered",
description: "By: koi/_flixel",
thumbnail: "/thumbs/11.png",
url: "/games/11/index.html",
  },
  {
id: 12,
title: "Baldi's Basics Plus",
description: "By: koi/_flixel, bread",
thumbnail: "/thumbs/12.png",
url: "/games/12/index.html",
  },
  {
id: 13,
title: "Baldi's Basics: Minus 3",
description: "By: bog/aukak",
thumbnail: "/thumbs/13.png",
url: "/games/13/index.html",
  },
  {
id: 14,
title: "Bat to Bed Demo",
description: "By: aj",
thumbnail: "/thumbs/14.png",
url: "/games/14/index.html",
  },
  {
id: 15,
title: "Bat to the Heavens",
description: "By: aj",
thumbnail: "/thumbs/15.png",
url: "/games/15/index.html",
  },
  {
id: 16,
title: "Bendy and The Ink Machine",
description: "By: 98Corbins, crackers, slant",
thumbnail: "/thumbs/16.png",
url: "/games/16/index.html",
  },
  {
id: 17,
title: "BERGENTRUCK 201x",
description: "By: bread",
thumbnail: "/thumbs/17.png",
url: "/games/17/index.html",
  },
  {
id: 18,
title: "BLOODMONEY!",
description: "By: bread",
thumbnail: "/thumbs/18.png",
url: "/games/18/index.html",
  },
  {
id: 19,
title: "boil Noodles at Night",
description: "By: sexyplankton/SomeRandomFella",
thumbnail: "/thumbs/19.png",
url: "/games/19/index.html",
  },
  {
id: 20,
title: "Buckshot Roulette",
description: "By: bread",
thumbnail: "/thumbs/20.png",
url: "/games/20/index.html",
  },
  {
id: 21,
title: "Brotato",
description: "By: BlueGameMC",
thumbnail: "#",
url: "/not.html",
  },
  {
id: 22,
title: "Capuchin",
description: "By: bog/aukak",
thumbnail: "/thumbs/22.png",
url: "/games/22/index.html",
  },
  {
id: 23,
title: "Chasing Tails ~A Promise in the Snow~ ",
description: "By: aj",
thumbnail: "/thumbs/23.png",
url: "/games/23/index.html",
  },
  {
id: 24,
title: "Cheese Rollers",
description: "By: sexyplankton/SomeRandomFella",
thumbnail: "/thumbs/24.png",
url: "/games/24/index.html",
  },
  {
id: 25,
title: "Christmas Massacre",
description: "By: 98corbins",
thumbnail: "/thumbs/25.png",
url: "/games/25/index.html",
  },
  {
id: 26,
title: "Class of '09",
description: "By: bread",
thumbnail: "/thumbs/26.png",
url: "/games/26/index.html",
  },
  {
id: 27,
title: "Clover Pit",
description: "By: bread",
thumbnail: "/thumbs/27.png",
url: "/games/27/index.html",
  },
  {
id: 28,
title: "Counter Strike & Half Life",
description: "By: x8BitRain",
thumbnail: "/thumbs/28.png",
url: "/games/28/index.html",
  },
  {
id: 29,
title: "Cuphead",
description: "By: bread, SpanishFreddy, koi/_flixel",
thumbnail: "/thumbs/29.png",
url: "/games/29/index.html",
  },
  {
id: 30,
title: "Celeste",
description: "By: Mercury Workshop, bread",
thumbnail: "/thumbs/30.png",
url: "/games/30/index.html",
  },
  {
id: 31,
title: "Celeste 3D",
description: "By: aj",
thumbnail: "/thumbs/31.png",
url: "/games/31/index.html",
  },
  {
id: 32,
title: "Cruelty Squad",
description: "By: dizzy",
thumbnail: "/thumbs/32.png",
url: "/games/32/index.html",
  },
  {
id: 33,
title: "Dead Plate",
description: "By: bread",
thumbnail: "/thumbs/33.png",
url: "/games/33/index.html",
  },
  {
id: 34,
title: "Deadseat",
description: "By: slqnt",
thumbnail: "/thumbs/34.png",
url: "/games/34/index.html",
  },
  {
id: 35,
title: "Dawnfolk",
description: "By: cirsius",
thumbnail: "/thumbs/35.png",
url: "/games/35/index.html",
  },
  {
id: 36,
title: "Dice a Million",
description: "By: NotRexed",
thumbnail: "/thumbs/36.png",
url: "/games/36/index.html",
  },
  {
id: 37,
title: "Dictators:No Peace Countryballs",
description: "By: bread",
thumbnail: "/thumbs/37.png",
url: "/games/37/index.html",
  },
  {
id: 38,
title: "Doki Doki Literature Club",
description: "By: EmeraldGreenR",
thumbnail: "/thumbs/38.png",
url: "/games/38/index.html",
  },
  {
id: 39,
title: "Do NOT Take This Cat Home",
description: "By: bread",
thumbnail: "/thumbs/39.png",
url: "/games/39/index.html",
  },
  {
id: 40,
title: "Doom Engine",
description: "By: GMH-Code",
thumbnail: "/thumbs/40.png",
url: "/games/40/index.html",
  },
  {
id: 41,
title: "Doom 3",
description: "By: 98corbins, gabrielcuvillier",
thumbnail: "/thumbs/41.png",
url: "/games/41/index.html",
  },
  {
id: 42,
title: "Duck Life Adventure",
description: "By: bog/aukak",
thumbnail: "/thumbs/42.png",
url: "/games/42/index.html",
  },
  {
id: 43,
title: "Dumb Ways to Die (v1.6)",
description: "By: bread",
thumbnail: "/thumbs/43.png",
url: "/games/43/index.html",
  },
  {
id: 44,
title: "Fear and Hunger",
description: "By: bread",
thumbnail: "/thumbs/44.png",
url: "/games/44/index.html",
  },
  {
id: 45,
title: "Fear and Hunger 2",
description: "By: bread",
thumbnail: "/thumbs/45.png",
url: "/games/45/index.html",
  },
  {
id: 46,
title: "Fears to Fathom: Home Alone",
description: "By: slqnt",
thumbnail: "/thumbs/46.png",
url: "/games/46/index.html",
  },
  {
id: 47,
title: "fish",
description: "By: bread",
thumbnail: "/thumbs/47.png",
url: "/games/47/index.html",
  },
  {
id: 48,
title: "FNAF",
description: "By: irv77",
thumbnail: "/thumbs/48.png",
url: "/games/48/index.html",
  },
  {
id: 49,
title: "Five Nights at Candy's 1",
description: "By: breadbb",
thumbnail: "/thumbs/49.png",
url: "/games/49/index.html",
  },
  {
id: 50,
title: "Five Nights at Candy's 2",
description: "By: breadbb",
thumbnail: "/thumbs/50.png",
url: "/games/50/index.html",
  },
  {
id: 51,
title: "Five Nighs at Epstein's",
description: "By: bread",
thumbnail: "/thumbs/51.png",
url: "/games/51/index.html",
  },
  {
id: 52,
title: "Five Nights at Freddy's World: Refreshed",
description: "By: Willowy",
thumbnail: "/thumbs/52.png",
url: "/games/52/index.html",
  },
  {
id: 53,
title: "Flying Gorilla",
description: "By: 98corbins",
thumbnail: "/thumbs/53.png",
url: "/games/53/index.html",
  },
  {
id: 54,
title: "Gabriel's Awesome Schoolhouse",
description: "By: bread",
thumbnail: "/thumbs/54.png",
url: "/games/54/index.html",
  },
  {
id: 55,
title: "Getting Over It",
description: "By: slqnt",
thumbnail: "/thumbs/55.png",
url: "/games/55/index.html",
  },
  {
id: 56,
title: "Gorilla Tag",
description: "By: boolonx dot com",
thumbnail: "/thumbs/56.png",
url: "/games/56/index.html",
  },
  {
id: 57,
title: "Granny",
description: "By: bread, bog/aukak",
thumbnail: "/thumbs/57.png",
url: "/games/57/index.html",
  },
  {
id: 58,
title: "GTA Vice City",
description: "By: DOS.Zone team",
thumbnail: "/thumbs/58.png",
url: "/games/58/index.html",
  },
  {
id: 59,
title: "Happy Sheepies",
description: "By: bread",
thumbnail: "/thumbs/59.png",
url: "/games/59/index.html",
  },
  {
id: 60,
title: "HAYAI",
description: "By: cirsius",
thumbnail: "/thumbs/60.png",
url: "/games/60/index.html",
  },
  {
id: 61,
title: "Helltaker",
description: "By: shayder",
thumbnail: "/thumbs/61.png",
url: "/games/61/index.html",
  },
  {
id: 62,
title: "Hotline Miami",
description: "By: 98Corbins",
thumbnail: "/thumbs/62.png",
url: "/games/62/index.html",
  },
  {
id: 63,
title: "Hollow Knight",
description: "By: bog/aukak",
thumbnail: "/thumbs/63.png",
url: "/games/63/index.html",
  },
  {
id: 64,
title: "Inscryption",
description: "By: reeyuki",
thumbnail: "/thumbs/64.png",
url: "/games/64/index.html",
  },
  {
id: 65,
title: "Iron Lung",
description: "By: 98Corbins",
thumbnail: "/thumbs/65.png",
url: "/games/65/index.html",
  },
  {
id: 66,
title: "I Spoke to God",
description: "By: gurtmuncher",
thumbnail: "/thumbs/66.png",
url: "/games/66/index.html",
  },
  {
id: 67,
title: "Jelly Drift",
description: "By: bread",
thumbnail: "/thumbs/67.png",
url: "/games/67/index.html",
  },
  {
id: 68,
title: "JENNY",
description: "By: NotDaniel",
thumbnail: "/thumbs/68.png",
url: "/games/68/index.html",
  },
  {
id: 69,
title: "Karlson",
description: "By: NPA",
thumbnail: "/thumbs/69.png",
url: "/games/69/index.html",
  },
  {
id: 70,
title: "Kill the Ice Age Baby Adventure 2",
description: "By: sexyplankton/SomeRandomFella",
thumbnail: "/thumbs/70.png",
url: "/games/70/index.html",
  },
  {
id: 71,
title: "Kindergarten 1 & 2",
description: "By: bread",
thumbnail: "/thumbs/71.png",
url: "/games/71/index.html",
  },
  {
id: 72,
title: "Kindergarten 3",
description: "By: slqnt",
thumbnail: "/thumbs/72.png",
url: "/games/72/index.html",
  },
  {
id: 73,
title: "Klifur",
description: "By: bog/aukak",
thumbnail: "/thumbs/73.png",
url: "/games/73/index.html",
  },
  {
id: 74,
title: "Lacey's Flash Games",
description: "By: bread",
thumbnail: "/thumbs/74.png",
url: "/games/74/index.html",
  },
  {
id: 75,
title: "Lethal Ape",
description: "By: 98Corbins",
thumbnail: "/thumbs/75.png",
url: "/games/75/index.html",
  },
  {
id: 76,
title: "Marble Blast Gold & Marble Blast Platinum",
description: "By: Vanilagy",
thumbnail: "/thumbs/76.png",
url: "/games/76/index.html",
  },
  {
id: 77,
title: "Milk inside a bag of milk inside a bag of milk",
description: "By: sky",
thumbnail: "/thumbs/77.png",
url: "/games/77/index.html",
  },
  {
id: 78,
title: "Milk outside a bag of milk outside a bag of milk",
description: "By: sky",
thumbnail: "/thumbs/78.png",
url: "/games/78/index.html",
  },
  {
id: 79,
title: "Milkman Karlson",
description: "By: bog/aukak",
thumbnail: "/thumbs/79.png",
url: "/games/79/index.html",
  },
  {
id: 80,
title: "MiSide",
description: "By: crackers",
thumbnail: "/thumbs/80.png",
url: "/games/80/index.html",
  },
  {
id: 81,
title: "My Dictator Stalin Can't Be This Cute ?!",
description: "By: cirsius",
thumbnail: "/thumbs/81.png",
url: "/games/81/index.html",
  },
  {
id: 82,
title: "Needy Streamer Overload",
description: "By: edurocks",
thumbnail: "/thumbs/82.png",
url: "/games/82/index.html",
  },
  {
id: 83,
title: "Nodebuster",
description: "By: cirsius",
thumbnail: "/thumbs/83.png",
url: "/games/83/index.html",
  },
  {
id: 84,
title: "Nothing",
description: "By: aj",
thumbnail: "/thumbs/84.png",
url: "/games/84/index.html",
  },
  {
id: 85,
title: "OMORI",
description: "By: bread",
thumbnail: "/thumbs/85.png",
url: "/games/85/index.html",
  },
  {
id: 86,
title: "Oneshot: World Machine Edition",
description: "By: Mercury Workshop",
thumbnail: "/thumbs/86.png",
url: "/games/86/index.html",
  },
  {
id: 87,
title: "Peaks of Yore",
description: "By: bread",
thumbnail: "/thumbs/87.png",
url: "/games/87/index.html",
  },
  {
id: 88,
title: "People Playground",
description: "By: 98Corbins, bog/aukak",
thumbnail: "/thumbs/88.png",
url: "/games/88/index.html",
  },
  {
id: 89,
title: "Pizza Tower",
description: "By: burnedpopcorn",
thumbnail: "/thumbs/89.png",
url: "/games/89/index.html",
  },
  {
id: 90,
title: "Plants vs Zombies: GOTY Edition",
description: "By: Zhou Qiankang",
thumbnail: "/thumbs/90.png",
url: "/games/90/index.html",
  },
  {
id: 91,
title: "Plants vs Zombies: Fusion",
description: "By: aj",
thumbnail: "/thumbs/91.png",
url: "/games/91/index.html",
  },
  {
id: 92,
title: "Portal",
description: "By: weliveinhell",
thumbnail: "/thumbs/92.png",
url: "/games/92/index.html",
  },
  {
id: 93,
title: "Quake",
description: "By: GMH-Code",
thumbnail: "/thumbs/93.png",
url: "/games/93/index.html",
  },
  {
id: 94,
title: "Quake 2",
description: "By: GMH-Code",
thumbnail: "/thumbs/94.png",
url: "/games/94/index.html",
  },
  {
id: 95,
title: "RAFT",
description: "By: unknown",
thumbnail: "/thumbs/95.png",
url: "/games/95/index.html",
  },
  {
id: 96,
title: "R.E.P.O",
description: "By: 98Corbins",
thumbnail: "/thumbs/96.png",
url: "/games/96/index.html",
  },
  {
id: 97,
title: "RE:RUN",
description: "By: bog/aukak",
thumbnail: "/thumbs/97.png",
url: "/games/97/index.html",
  },
  {
id: 98,
title: "Running Fred",
description: "By: bog/aukak",
thumbnail: "/thumbs/98.png",
url: "/games/98/index.html",
  },
  {
id: 99,
title: "Scoutdingo",
description: "By: burnedpopcorn",
thumbnail: "/thumbs/99.png",
url: "/games/99/index.html",
  },
  {
id: 100,
title: "Shift at Midnight",
description: "By: slqnt",
thumbnail: "/thumbs/100.png",
url: "/games/100/index.html",
  },
  {
id: 101,
title: "Slender: The Eight Pages",
description: "By: bread",
thumbnail: "/thumbs/101.png",
url: "/games/101/index.html",
  },
  {
id: 102,
title: "Slime Ranchers",
description: "By: snubby",
thumbnail: "/thumbs/102.png",
url: "/games/102/index.html",
  },
  {
id: 103,
title: "Something",
description: "By: aj",
thumbnail: "/thumbs/103.png",
url: "/games/103/index.html",
  },
  {
id: 104,
title: "Sonic CD",
description: "By: TWS2401",
thumbnail: "/thumbs/104.png",
url: "/games/104/index.html",
  },
  {
id: 105,
title: "Sonic the Hedgehog (2013)",
description: "By: MattConn, VinMannie",
thumbnail: "/thumbs/105.png",
url: "/games/105/index.html",
  },
  {
id: 106,
title: "Sonic the Hedgehog 2",
description: "By: MattConn, VinMannie",
thumbnail: "/thumbs/106.png",
url: "/games/106/index.html",
  },
  {
id: 107,
title: "Sonic Mania",
description: "By: VinMannie",
thumbnail: "/thumbs/107.png",
url: "/games/107/index.html",
  },
  {
id: 108,
title: "Sonic Robo Blast 2",
description: "By: chromaticpipe",
thumbnail: "/thumbs/108.png",
url: "/games/108/index.html",
  },
  {
id: 109,
title: "Speed Stars",
description: "By: 98Corbins",
thumbnail: "/thumbs/109.png",
url: "/games/109/index.html",
  },
  {
id: 110,
title: "S.P.L.I.T",
description: "By: gurtmuncher",
thumbnail: "/thumbs/110.png",
url: "/games/110/index.html",
  },
  {
id: 111,
title: "Stardew Valley",
description: "By: cirsius",
thumbnail: "/thumbs/111.png",
url: "/games/111/index.html",
  },
  {
id: 112,
title: "SRB2 Kart",
description: "By: skyleite",
thumbnail: "/thumbs/112.png",
url: "/games/112/index.html",
  },
  {
id: 113,
title: "Super Mario 64 FPS",
description: "By: aj",
thumbnail: "/thumbs/113.png",
url: "/games/113/index.html",
  },
  {
id: 114,
title: "Sunky's Schoolhouse",
description: "By: aj",
thumbnail: "/thumbs/114.png",
url: "/games/114/index.html",
  },
  {
id: 115,
title: "Terraria",
description: "By: bread",
thumbnail: "/thumbs/115.png",
url: "/games/115/index.html",
  },
  {
id: 116,
title: "That's Not My Neighbor",
description: "By: bread",
thumbnail: "/thumbs/116.png",
url: "/games/116/index.html",
  },
  {
id: 117,
title: "The Man From the Window",
description: "By: bread",
thumbnail: "/thumbs/117.png",
url: "/games/117/index.html",
  },
  {
id: 118,
title: "The Man From the Window 2",
description: "By: unknown",
thumbnail: "/thumbs/118.png",
url: "/games/118/index.html",
  },
  {
id: 119,
title: "Touhou Mother",
description: "By: bog/aukak",
thumbnail: "/thumbs/119.png",
url: "/games/119/index.html",
  },
  {
id: 120,
title: "Traffic Racer",
description: "By: bread",
thumbnail: "/thumbs/120.png",
url: "/games/120/index.html",
  },
  {
id: 121,
title: "TriZon",
description: "By: cirsius",
thumbnail: "/thumbs/121.png",
url: "/games/121/index.html",
  },
  {
id: 122,
title: "Ultrakill Prelude",
description: "By: 98Corbins",
thumbnail: "/thumbs/122.png",
url: "/games/122/index.html",
  },
  {
id: 123,
title: "Ultrapool",
description: "By: ParrrotVR, bread",
thumbnail: "/thumbs/123.png",
url: "/games/123/index.html",
  },
  {
id: 124,
title: "Undertale",
description: "By: burnedpopcorn",
thumbnail: "/thumbs/124.png",
url: "/games/124/index.html",
  },
  {
id: 125,
title: "Undertale Yellow",
description: "By: burnedpopcorn",
thumbnail: "/thumbs/125.png",
url: "/games/125/index.html",
  },
  {
id: 126,
title: "Unreal Gold",
description: "By: unknown",
thumbnail: "/thumbs/126.png",
url: "/games/126/index.html",
  },
  {
id: 127,
title: "Untitled Goose Game",
description: "By: bog/aukak",
thumbnail: "/thumbs/127.png",
url: "/games/127/index.html",
  },
  {
id: 128,
title: "Upload Labs",
description: "By: thecheetoman",
thumbnail: "/thumbs/128.png",
url: "/games/128/index.html",
  },
  {
id: 129,
title: "Upstream",
description: "By: gurtmuncher",
thumbnail: "/thumbs/129.png",
url: "/games/129/index.html",
  },
  {
id: 130,
title: "Void Whispers",
description: "By: cirsius",
thumbnail: "/thumbs/130.png",
url: "/games/130/index.html",
  },
  {
id: 131,
title: "Webfishing",
description: "By: bread",
thumbnail: "/thumbs/131.png",
url: "/games/131/index.html",
  },
  {
id: 132,
title: "Who's Your Daddy?",
description: "By: reeyuki",
thumbnail: "/thumbs/132.png",
url: "/games/132/index.html",
  },
  {
id: 133,
title: "Witch's Heart",
description: "By: bread",
thumbnail: "/thumbs/133.png",
url: "/games/133/index.html",
  },
  {
id: 134,
title: "Xash3D",
description: "By: unknown",
thumbnail: "/thumbs/134.png",
url: "/games/134/index.html",
  },
  {
id: 135,
title: "You Want Half a Mounds Bar",
description: "By: unknown",
thumbnail: "/thumbs/135.png",
url: "/games/135/index.html",
  },
  {
id: 136,
title: "Your Only Move is Hustle",
description: "By: bog/aukak",
thumbnail: "/thumbs/136.png",
url: "/games/136/index.html",
  },
  {
id: 137,
title: "Yume Nikki",
description: "By: bread",
thumbnail: "/thumbs/137.png",
url: "/games/137/index.html",
  },
];