const GAMES = [
  {
    id: 1,
    title: "TEST",
    description: "By: ME",
    thumbnail: "#",
    url: "#",
  },
  {
id: 2,
title: "Amanda The Adventurer",
description: "By: bread",
thumbnail: "/thumbs/2.png",
url: "/games/2/index.html",
  },
  {
id: 3,
title: "Andy's Apple Farm",
description: "By: bread",
thumbnail: "/thumbs/3.png",
url: "/games/3/index.html",
  },
  {
id: 4,
title: "Antonblast",
description: "By: burnedpopcorn",
thumbnail: "/thumbs/4.png",
url: "/games/4/index.html",
  },
  {
id: 5,
title: "A Difficult Game About Climbing",
description: "By: bread",
thumbnail: "/thumbs/5.png",
url: "/games/5/index.html",
  },
  {
id: 6,
title: "Apotheon",
description: "By: gurtmuncher",
thumbnail: "/thumbs/6.png",
url: "/games/6/index.html",
  },
  {
id: 7,
title: "Approaches",
description: "By: shayder",
thumbnail: "/thumbs/7.png",
url: "/games/7/index.html",
  },
  {
id: 8,
title: "Arco",
description: "By: cirsius",
thumbnail: "/thumbs/8.png",
url: "/games/8/index.html",
  },
  {
id: 9,
title: "Balatro",
description: "By: W0W53R",
thumbnail: "/thumbs/9.png",
url: "/games/9/index.html",
  },
  {
id: 10,
title: "Baldi's Basics Birthday Bash",
description: "By: crackers",
thumbnail: "/thumbs/10.png",
url: "/games/10/index.html",
  },
  {
id: 11,
title: "Baldi's Basics Classic Remastered",
description: "By: koi/_flixel",
thumbnail: "/thumbs/11.png",
url: "/games/11/index.html",
  },
  {
id: 12,
title: "Baldi's Basics Plus",
description: "By: koi/_flixel, bread",
thumbnail: "/thumbs/12.png",
url: "/games/12/index.html",
  },
  {
id: 13,
title: "Baldi's Basics: Minus 3",
description: "By: bog/aukak",
thumbnail: "/thumbs/13.png",
url: "/games/13/index.html",
  },
  {
id: 14,
title: "Bat to Bed Demo",
description: "By: aj",
thumbnail: "/thumbs/14.png",
url: "/games/14/index.html",
  },
  {
id: 15,
title: "Bat to the Heavens",
description: "By: aj",
thumbnail: "/thumbs/15.png",
url: "/games/15/index.html",
  },
  {
id: 16,
title: "Bendy and The Ink Machine",
description: "By: 98Corbins, crackers, slant",
thumbnail: "/thumbs/16.png",
url: "/games/16/index.html",
  },
  {
id: 17,
title: "BERGENTRUCK 201x",
description: "By: bread",
thumbnail: "/thumbs/17.png",
url: "/games/17/index.html",
  },
  {
id: 18,
title: "BLOODMONEY!",
description: "By: bread",
thumbnail: "/thumbs/18.png",
url: "/games/18/index.html",
  },
  {
id: 19,
title: "boil Noodles at Night",
description: "By: sexyplankton/SomeRandomFella",
thumbnail: "/thumbs/19.png",
url: "/games/19/index.html",
  },
  {
id: 20,
title: "Buckshot Roulette",
description: "By: bread",
thumbnail: "/thumbs/20.png",
url: "/games/20/index.html",
  },
  {
id: 21,
title: "Brotato",
description: "By: BlueGameMC",
thumbnail: "#",
url: "/not.html",
  },
  {
id: 22,
title: "Capuchin",
description: "By: bog/aukak",
thumbnail: "/thumbs/22.png",
url: "/games/22/index.html",
  },
  {
id: 23,
title: "Chasing Tails ~A Promise in the Snow~ ",
description: "By: aj",
thumbnail: "/thumbs/23.png",
url: "/games/23/index.html",
  },
  {
id: 24,
title: "Cheese Rollers",
description: "By: sexyplankton/SomeRandomFella",
thumbnail: "/thumbs/24.png",
url: "/games/24/index.html",
  },
  {
id: 25,
title: "Christmas Massacre",
description: "By: 98corbins",
thumbnail: "/thumbs/25.png",
url: "/games/25/index.html",
  },
  {
id: 26,
title: "Class of '09",
description: "By: bread",
thumbnail: "/thumbs/26.png",
url: "/games/26/index.html",
  },
  {
id: 27,
title: "Clover Pit",
description: "By: bread",
thumbnail: "/thumbs/27.png",
url: "/games/27/index.html",
  },
  {
id: 28,
title: "Counter Strike & Half Life",
description: "By: x8BitRain",
thumbnail: "/thumbs/28.png",
url: "/games/28/index.html",
  },
  {
id: 29,
title: "Cuphead",
description: "By: bread, SpanishFreddy, koi/_flixel",
thumbnail: "/thumbs/29.png",
url: "/games/29/index.html",
  },
  {
id: 30,
title: "Celeste",
description: "By: Mercury Workshop, bread",
thumbnail: "/thumbs/30.png",
url: "/games/30/index.html",
  },
  {
id: 31,
title: "Celeste 3D",
description: "By: aj",
thumbnail: "/thumbs/31.png",
url: "/games/31/index.html",
  },
  {
id: 32,
title: "Cruelty Squad",
description: "By: dizzy",
thumbnail: "/thumbs/32.png",
url: "/games/32/index.html",
  },
  {
id: 33,
title: "Dead Plate",
description: "By: bread",
thumbnail: "/thumbs/33.png",
url: "/games/33/index.html",
  },
  {
id: 34,
title: "Deadseat",
description: "By: slqnt",
thumbnail: "/thumbs/34.png",
url: "/games/34/index.html",
  },
  {
id: 35,
title: "Dawnfolk",
description: "By: cirsius",
thumbnail: "/thumbs/35.png",
url: "/games/35/index.html",
  },
  {
id: 36,
title: "Dice a Million",
description: "By: NotRexed",
thumbnail: "/thumbs/36.png",
url: "/games/36/index.html",
  },
  {
id: 37,
title: "Dictators:No Peace Countryballs",
description: "By: bread",
thumbnail: "/thumbs/37.png",
url: "/games/37/index.html",
  },
  {
id: 38,
title: "Doki Doki Literature Club",
description: "By: EmeraldGreenR",
thumbnail: "/thumbs/38.png",
url: "/games/38/index.html",
  },
  {
id: 39,
title: "Do NOT Take This Cat Home",
description: "By: bread",
thumbnail: "/thumbs/39.png",
url: "/games/39/index.html",
  },
  {
id: 40,
title: "Doom Engine",
description: "By: GMH-Code",
thumbnail: "/thumbs/40.png",
url: "/games/40/index.html",
  },
  {
id: 41,
title: "Doom 3",
description: "By: 98corbins, gabrielcuvillier",
thumbnail: "/thumbs/41.png",
url: "/games/41/index.html",
  },
  {
id: 42,
title: "Duck Life Adventure",
description: "By: bog/aukak",
thumbnail: "/thumbs/42.png",
url: "/games/42/index.html",
  },
  {
id: 43,
title: "Dumb Ways to Die (v1.6)",
description: "By: bread",
thumbnail: "/thumbs/43.png",
url: "/games/43/index.html",
  },
  {
id: 44,
title: "Fear and Hunger",
description: "By: bread",
thumbnail: "/thumbs/44.png",
url: "/games/44/index.html",
  },
  {
id: 45,
title: "Fear and Hunger 2",
description: "By: bread",
thumbnail: "/thumbs/45.png",
url: "/games/45/index.html",
  },
  {
id: 46,
title: "Fears to Fathom: Home Alone",
description: "By: slqnt",
thumbnail: "/thumbs/46.png",
url: "/games/46/index.html",
  },
  {
id: 47,
title: "fish",
description: "By: bread",
thumbnail: "/thumbs/47.png",
url: "/games/47/index.html",
  },
];